@echo off
rem Windows-side paths, called by scripts\windows\*.bat.
rem Defaults match the reference machine. To change them, do NOT edit this file:
rem copy config\paths.local.example.bat to config\paths.local.bat (gitignored) and override there.

rem Project root, auto-detected from this file's location
for %%i in ("%~dp0..") do set "PROJECT_DIR=%%~fi"

rem WSL distro that holds LiveTalking + the Python envs (NOT the machine's default distro)
set WSL_DISTRO=Ubuntu-24.04

rem llama.cpp + Qwen3-14B GGUF (external, not in this repo)
set LLAMA_DIR=E:\llama.cpp
set LLAMA_MODEL=E:\llama.cpp\models\Qwen3-14B-Q4_K_M.gguf
set LLAMA_PORT=8090
set LLAMA_ARGS=-np 1 -c 8192 -fa on --temp 1.0 --top-p 0.95 --host 0.0.0.0 --port %LLAMA_PORT%

rem ComfyUI portable (external) - only needed to regenerate assets\avatar\idle.mp4
set COMFY_DIR=E:\ComfyUI_windows_portable
set COMFY_PORT=8188

rem Demo page
set DEMO_URL=http://localhost:8010/cyber_gf/web/cyber_gf_demo.html

rem machine-local overrides (gitignored)
if exist "%~dp0paths.local.bat" call "%~dp0paths.local.bat"

rem WSL view of the project root (e.g. /mnt/c/.../cyber_gf), derived with wslpath inside %WSL_DISTRO%
set "_PF=%PROJECT_DIR:\=/%"
for /f "delims=" %%i in ('wsl -d %WSL_DISTRO% --exec wslpath -a "%_PF%"') do set "PROJECT_WSL=%%i"
set "_PF="
